# Problem 12
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

# Here we use the fact that in order to find divisors of n
# we seek for pairs (m, n/m) where m < n/m.

i <- 1
divisors <- c()

while (length(divisors) < 501) {
  
  divisors <- c()
  triangle_numer <- sum(1:i)
  
  for (m in 1:sqrt(triangle_numer)) {
    if (triangle_numer %% m == 0){
      divisors <- c(divisors, m, triangle_numer/m)
    }
  }
  
  i <- i + 1
}






