# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci_sequence <- c(1, 2)
i <- 2
last_term <- fibonacci_sequence[i]

while (last_term < 4e6) {
  last_term <- fibonacci_sequence[i]
  i <- i + 1
  fibonacci_sequence[i] <- fibonacci_sequence[i-1] + fibonacci_sequence[i-2]
}

result <- fibonacci_sequence[fibonacci_sequence %% 2 == 0]
sum(result)